name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service name"
        required: true
        default: "hello"
      branch:
        description: "Git branch"
        required: true
        default: "main"
      environment:
        description: "Target environment"
        required: true
        default: "dev"
      brands:
        description: "CSV file with brand list"
        required: true
        default: "brands.csv"
      chartVersion:
        description: "Helm chart version"
        required: true
        default: "1.0.0"
      build:
        description: "Build and push image?"
        required: true
        default: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
      SERVICE: ${{ inputs.service }}
      ENVIRONMENT: ${{ inputs.environment }}

    steps:
      # ðŸ§© Checkout code
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      # ðŸ§© AWS auth
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ðŸ§© Setup kubeconfig (EKS)
      - name: Setup kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      # ðŸ§© Build + Push image (optional)
      - name: Build and push to ECR
        if: ${{ inputs.build == 'true' }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # ðŸ§© Deploy with Helm + track version
      - name: Deploy per brand via Helm
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          echo "ðŸš€ Starting deploy for service: ${SERVICE}"

          # Ensure ConfigMap exists
          kubectl get configmap release-tracker -n ${ENVIRONMENT} >/dev/null 2>&1 || \
            kubectl create configmap release-tracker -n ${ENVIRONMENT} --from-literal=init="true"

          while IFS=',' read id brand domain; do
            [ "$brand" = "brand" ] && continue
            echo "ðŸ“¦ Deploying brand: $brand"

            helm upgrade --install ${SERVICE}-${brand} charts/${SERVICE} \
              -n ${ENVIRONMENT} \
              --set image.repository=${ECR_REGISTRY}/${ECR_REPO_NAME} \
              --set image.tag=${IMAGE_TAG} \
              --set brand=${brand} \
              --set env=${ENVIRONMENT} \
              --set commit=${GITHUB_SHA} \
              --version ${{ inputs.chartVersion }}

            # ðŸ”– Update release-tracker safely
            kubectl patch configmap release-tracker -n ${ENVIRONMENT} \
              --type merge \
              -p "{\"data\": {\"${SERVICE}-${brand}\": \"tag:${IMAGE_TAG}, commit:${GITHUB_SHA}, chart:${{ inputs.chartVersion }}\"}}"

          done < ${{ inputs.brands }}

      # ðŸ§© Show release status
      - name: Check outdated releases
        run: |
          echo "ðŸ§¾ Current deployed versions:"
          kubectl get configmap release-tracker -n ${ENVIRONMENT} -o jsonpath='{.data}' | jq .

          echo "ðŸ” Checking outdated brands..."
          for k in $(kubectl get configmap release-tracker -n ${ENVIRONMENT} -o jsonpath='{.data}' | jq -r 'keys[]'); do
            val=$(kubectl get configmap release-tracker -n ${ENVIRONMENT} -o jsonpath="{.data.${k}}" )
            if [[ $val != *"${GITHUB_SHA}"* ]]; then
              echo "âš ï¸ Brand $k is outdated â†’ $val"
            fi
          done
